#!/usr/bin/env python3
"""Validate the PL register schema and generate C/SystemVerilog bindings."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "specs" / "neptune-pl-registers-v1.json"
C_OUTPUT = ROOT / "protocol" / "generated" / "neptune_pl_registers_v1.h"
PS_C_OUTPUT = ROOT / "ps" / "include" / "neptune_pl_registers_v1.h"
SV_OUTPUT = ROOT / "hdl" / "rtl" / "generated" / "neptune_pl_registers_v1_pkg.sv"


def load_validate() -> dict:
    value = json.loads(SPEC.read_text(encoding="utf-8"))
    if value.get("schema") != "neptunesdr.pl-register-map/v1":
        raise ValueError("unsupported PL register schema")
    span = value.get("address_span_bytes")
    registers = value.get("registers")
    if not isinstance(span, int) or span <= 0 or not isinstance(registers, list) or not registers:
        raise ValueError("invalid register span/list")
    names = set()
    offsets = set()
    for register in registers:
        name = register.get("name")
        offset = register.get("offset")
        if not isinstance(name, str) or not name or name in names:
            raise ValueError("register names must be unique")
        if not isinstance(offset, int) or offset < 0 or offset >= span or offset % 4 or offset in offsets:
            raise ValueError("register offsets must be unique aligned words in range")
        if register.get("access") not in {"RO", "RW", "WO", "W1C"}:
            raise ValueError("unsupported access for %s" % name)
        reset = register.get("reset")
        if not isinstance(reset, int) or not 0 <= reset <= 0xFFFFFFFF:
            raise ValueError("invalid reset for %s" % name)
        if not isinstance(register.get("description"), str) or not register["description"]:
            raise ValueError("missing description for %s" % name)
        names.add(name)
        offsets.add(offset)
    required = {"SAMPLE_COUNT_LO", "SAMPLE_COUNT_HI", "TX_PERSISTENT_INHIBIT", "TX_DISARM"}
    if not required.issubset(names):
        raise ValueError("register map omits required safety/time contacts")
    by_name = {item["name"]: item for item in registers}
    if value.get("magic") != int.from_bytes(b"NEPT", "little") or by_name["MAGIC"]["reset"] != value["magic"]:
        raise ValueError("PL magic must encode ASCII NEPT consistently")
    if by_name["TX_PERSISTENT_INHIBIT"]["reset"] != 1:
        raise ValueError("TX persistent inhibit must reset asserted")
    capabilities = value.get("capability_bits")
    if not isinstance(capabilities, dict) or not capabilities:
        raise ValueError("register map needs capability bits")
    capability_positions = set()
    for name, bit in capabilities.items():
        if (
            not isinstance(name, str)
            or not name
            or isinstance(bit, bool)
            or not isinstance(bit, int)
            or not 0 <= bit < 32
            or bit in capability_positions
        ):
            raise ValueError("capability bits must be unique named positions")
        capability_positions.add(bit)
    fields = value.get("register_fields")
    if not isinstance(fields, dict) or not fields:
        raise ValueError("register map needs canonical register fields")
    for register_name, register_fields in fields.items():
        if register_name not in by_name or not isinstance(register_fields, dict) or not register_fields:
            raise ValueError("invalid field register %s" % register_name)
        occupied = 0
        for field_name, field in register_fields.items():
            if not isinstance(field_name, str) or not field_name or not isinstance(field, dict):
                raise ValueError("invalid field in %s" % register_name)
            lsb = field.get("lsb")
            width = field.get("width")
            if (
                isinstance(lsb, bool)
                or not isinstance(lsb, int)
                or isinstance(width, bool)
                or not isinstance(width, int)
                or lsb < 0
                or width <= 0
                or lsb + width > 32
            ):
                raise ValueError("invalid bit range for %s.%s" % (register_name, field_name))
            mask = ((1 << width) - 1) << lsb
            if occupied & mask:
                raise ValueError("overlapping fields in %s" % register_name)
            occupied |= mask
    return value


def render(value: dict) -> tuple[str, str]:
    digest = hashlib.sha256(SPEC.read_bytes()).hexdigest()
    c_lines = [
        "/* Generated by scripts/generate_registers.py; DO NOT EDIT. */",
        "#ifndef NEPTUNE_PL_REGISTERS_V1_H",
        "#define NEPTUNE_PL_REGISTERS_V1_H",
        '#define NEPTUNE_PL_REGISTERS_SPEC_SHA256 "%s"' % digest,
        "#define NEPTUNE_PL_ABI_VERSION 0x%08xU" % value["abi_version"],
        "#define NEPTUNE_PL_MAGIC 0x%08xU" % value["magic"],
        "#define NEPTUNE_PL_SPAN_BYTES 0x%08xU" % value["address_span_bytes"],
    ]
    sv_lines = [
        "// Generated by scripts/generate_registers.py; DO NOT EDIT.",
        "package neptune_pl_registers_v1_pkg;",
        '  localparam string SPEC_SHA256 = "%s";' % digest,
        "  localparam logic [31:0] ABI_VERSION = 32'h%08x;" % value["abi_version"],
        "  localparam logic [31:0] MAGIC = 32'h%08x;" % value["magic"],
    ]
    for register in value["registers"]:
        c_lines.append("#define NEPTUNE_PL_REG_%s 0x%04xU" % (register["name"], register["offset"]))
        sv_lines.append("  localparam logic [11:0] REG_%s = 12'h%03x;" % (register["name"], register["offset"]))
    for name, bit in value["capability_bits"].items():
        c_lines.append("#define NEPTUNE_PL_CAP_%s 0x%08xU" % (name, 1 << bit))
        sv_lines.append("  localparam logic [31:0] CAP_%s = 32'h%08x;" % (name, 1 << bit))
    for register_name, fields in value["register_fields"].items():
        for field_name, field in fields.items():
            lsb = field["lsb"]
            mask = ((1 << field["width"]) - 1) << lsb
            prefix = "%s_%s" % (register_name, field_name)
            c_lines.append("#define NEPTUNE_PL_FIELD_%s_SHIFT %dU" % (prefix, lsb))
            c_lines.append("#define NEPTUNE_PL_FIELD_%s_MASK 0x%08xU" % (prefix, mask))
            sv_lines.append("  localparam int unsigned FIELD_%s_SHIFT = %d;" % (prefix, lsb))
            sv_lines.append("  localparam logic [31:0] FIELD_%s_MASK = 32'h%08x;" % (prefix, mask))
    c_lines.extend(("#endif", ""))
    sv_lines.extend(("endpackage", ""))
    return "\n".join(c_lines), "\n".join(sv_lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    c_text, sv_text = render(load_validate())
    outputs = ((C_OUTPUT, c_text), (PS_C_OUTPUT, c_text), (SV_OUTPUT, sv_text))
    if args.check:
        stale = [str(path.relative_to(ROOT)) for path, text in outputs if not path.is_file() or path.read_text(encoding="utf-8") != text]
        if stale:
            raise SystemExit("stale generated register bindings: " + ", ".join(stale))
    else:
        for path, text in outputs:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
    print("NEPTUNE_PL_REGISTERS_V1_GENERATED PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
